/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webhost_free: (a: number, b: number) => void;
export const encodeMeshAsset: (a: number, b: number, c: number) => void;
export const encodeSceneAnchorSet: (a: number, b: number, c: number) => void;
export const hydratePlaylistEntry: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const loadGlbScene: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const main: () => void;
export const maxDisplayDurationSeconds: () => number;
export const minDisplayDurationSeconds: () => number;
export const parseSecretsJson: (a: number, b: number, c: number) => void;
export const validateEntryParams: (a: number, b: number, c: number, d: number, e: number) => void;
export const webhost_downloadTrace: (a: number, b: number, c: number) => number;
export const webhost_exportTrace: (a: number) => number;
export const webhost_frame: (a: number, b: number, c: number) => void;
export const webhost_loadBundle: (a: number, b: number, c: number) => number;
export const webhost_loadSlide: (a: number, b: number, c: number) => number;
export const webhost_new: (a: number, b: number, c: number) => void;
export const webhost_setScreensaverConfig: (a: number, b: number, c: number) => void;
export const webhost_startTraceCapture: (a: number, b: number) => number;
export const webhost_stats: (a: number) => number;
export const webhost_stopTraceCapture: (a: number, b: number) => number;
export const webhost_teardown: (a: number) => void;
export const __wasm_bindgen_func_elem_3421: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_3428: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
